/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import principal.Principal;

/**
 *
 * @author jefadmin
 */
public class TelaSignup extends javax.swing.JFrame {

    /**
     * Creates new form TelaSignup
     */
    public TelaSignup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        inpSignupSenha1 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        inpSignupSenha2 = new javax.swing.JPasswordField();
        inpSignupEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btSignupRegistrar = new javax.swing.JButton();
        btSignupCancelar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        inpSignupNome = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("O seu nome real");

        jLabel2.setText("Crie uma senha forte");

        jLabel3.setText("Confirme a senha");

        inpSignupSenha2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpSignupSenha2ActionPerformed(evt);
            }
        });

        inpSignupEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpSignupEmailActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel5.setText("Nova conta");

        btSignupRegistrar.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        btSignupRegistrar.setText("Registrar");
        btSignupRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSignupRegistrarActionPerformed(evt);
            }
        });

        btSignupCancelar.setForeground(new java.awt.Color(153, 0, 0));
        btSignupCancelar.setText("Cancelar");
        btSignupCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSignupCancelarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Controle de Estoque");

        inpSignupNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inpSignupNomeActionPerformed(evt);
            }
        });

        jLabel6.setText("O seu email");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 98, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(inpSignupSenha1)
                        .addComponent(inpSignupSenha2)
                        .addComponent(inpSignupEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(inpSignupNome, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btSignupCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btSignupRegistrar)))
                .addGap(68, 68, 68))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel4)
                .addGap(31, 31, 31)
                .addComponent(jLabel5)
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(7, 7, 7)
                .addComponent(inpSignupNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(inpSignupEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inpSignupSenha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inpSignupSenha2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSignupCancelar)
                    .addComponent(btSignupRegistrar))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inpSignupSenha2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpSignupSenha2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpSignupSenha2ActionPerformed

    private void inpSignupEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpSignupEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpSignupEmailActionPerformed
    
    // Botão para tentar um cadastro com as informações
    // preenchidas pelo usuário
    private void btSignupRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSignupRegistrarActionPerformed
        // TODO add your handling code here:
        String nome = inpSignupNome.getText();
        String email = inpSignupEmail.getText();
        String senha1 = new String(inpSignupSenha1.getPassword());
        String senha2 = new String(inpSignupSenha2.getPassword());
        String[] inputs = {nome,email,senha1,senha2};
        boolean erro = false;
        // Verificar se algum campo não foi preenchido
        for(int i=0; i<inputs.length; i++){
            if(inputs[i].isEmpty()){
                JOptionPane.showMessageDialog(null, "Erro - Preencha todos os campos.");
                erro = true;
                break;
            }
        }
        // Verificar se o email fornecido já existe no banco de dados
        if(GerenciaTelas.usuarioControle.emailRegistrado(email)){
            JOptionPane.showMessageDialog(null, "Erro - Este email já foi registrado.");
            erro = true;
        }
        // Verificar se as senhas correspondem
        if(senha1.equals(senha2)==false){
            JOptionPane.showMessageDialog(null, "Erro - As senhas não correspondem.");
            erro = true;
        }
        // Se nenhum erro encontrado, prosseguir com o cadastro
        if(!erro){
            try{
                GerenciaTelas.usuarioControle.cadastrar(email, senha2, nome);
                JOptionPane.showMessageDialog(null, "Conta registrada com sucesso!");
                GerenciaTelas.definirTelaAtual("login");
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, "Erro ao registrar conta.");
            }
        }
    }//GEN-LAST:event_btSignupRegistrarActionPerformed

    private void btSignupCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSignupCancelarActionPerformed
        // TODO add your handling code here:
        GerenciaTelas.definirTelaAtual("login");
    }//GEN-LAST:event_btSignupCancelarActionPerformed

    private void inpSignupNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inpSignupNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inpSignupNomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaSignup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSignupCancelar;
    private javax.swing.JButton btSignupRegistrar;
    private javax.swing.JTextField inpSignupEmail;
    private javax.swing.JTextField inpSignupNome;
    private javax.swing.JPasswordField inpSignupSenha1;
    private javax.swing.JPasswordField inpSignupSenha2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
